apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bmi-webapp
  name: bmi-webapp
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
    nodePort: 30301
    protocol: TCP
  type: NodePort
  selector:
    io.kompose.service: bmi-webapp
status:
  loadBalancer: {}
