apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bmi-calculator
  name: bmi-calculator
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bmi-calculator
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Dcse.service.registry.address=http://sc.servicecomb.io:30100
        - name: JAR_NAME
          value: calculator-0.4.0-SNAPSHOT
        image: calculator:0.4.0-SNAPSHOT
        name: bmi-calculator
#        ports:
#        - containerPort: 8888
        resources:
          requests:
            cpu: 200m
      restartPolicy: Always
status: {}
